### ISSUE TITLE
No working

### ISSUE THREAD

**Issue by zodiaccong** [Ondkloss/cg-candy-collector#1]
I install it but it's not working

**Comment by Ondkloss** [comment]
Thanks for the report. I have not updated or used this myself for some time, but I will do a review of the functionality.

**Comment by Ondkloss** [comment]
Thanks for the report. I have not updated or used this myself for some time, but I will do a review of the functionality.

**Comment by Ondkloss** [comment]
Thanks for your report! It appears they changed the "clickable button" from an `input` element to a `button` element.
I haven't been able to test the roll over to a new day (since a day hasn't passed and I have no good way to mock it), but I'm assuming that interaction hasn't changed.

The update has been pushed to both Chrome and Firefox extensions, but may take some time to be approved. Thanks again!
